### ISSUE TITLE
azure_rm_deployment - syntax check conflicts with REST API URI

### ISSUE THREAD

**Issue by adosztal** [ansible-collections/azure#259]
##### SUMMARY
The `deployment_name` variable is used as part of the URI used for the REST API call: https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/{deploymentName}?api-version=2019-10-01

However some resources have subresources. I tried to deploy a VM extension for `MyVM` to join it to a domain, which should be done by using the following URL:
[https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/**MyVM/joindomain**?api-version=2019-10-01](https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/MyVM/joindomain?api-version=2019-10-01)

The easiest way to deploy this ARM template would using the `MyVM/joindomain` as the `deployment_name`. The problem is the syntax check doesn't allow slashes in this variable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
<NULL return>
```

##### OS / ENVIRONMENT
AWX 14.0 container running on Ubuntu 20.04.1

##### STEPS TO REPRODUCE
I used this task:
```yaml
- name: Join VM to AD
  azure_rm_deployment:
    resource_group: "MyRG"
    name: "MyVM/joindomain"
    location: "{{ region }}"
    template:
      $schema: "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      variables:
        location: "{{ region }}"
        dnsLabelPrefix: "{{ domain_name }}"
        domainUsername: "{{ lookup('env', 'DOMAIN_ADMIN') }}"
        domainPassword: "{{ lookup('env', 'DOMAIN_ADMIN_PASSWORD') }}"
      resources:
        - apiVersion: "2015-06-15"
          type: Microsoft.Compute/virtualMachines/extensions
          name: "[concat(variables('dnsLabelPrefix'),'/joindomain')]"
          location: "[variables('location')]"
          dependsOn:
            - "[concat('Microsoft.Compute/virtualMachines/', variables('dnsLabelPrefix'))]"
          properties:
            publisher: "Microsoft.Compute"
            type: "JsonADDomainExtension"
            typeHandlerVersion: "1.3"
            autoUpgradeMinorVersion: true
            settings:
              Name: "[variables('dnsLabelPrefix')]"
              User: "[concat(variables('dnsLabelPrefix'), '\\', variables('domainUsername'))]"
              Restart: 'true'
            protectedSettings:
              Password: "[variables('domainPassword')]"
```

##### EXPECTED RESULTS
I expected the template to be deployed.

##### ACTUAL RESULTS
```paste below
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_deployment', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 702, in <module>\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 698, in main\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 471, in __init__\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py\", line 348, in __init__\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 479, in exec_module\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 554, in deploy_template\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py\", line 279, in create_or_update\n    **operation_config\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py\", line 199, in _create_or_update_initial\n    'deploymentName': self._serialize.url(\"deployment_name\", deployment_name, 'str', max_length=64, min_length=1, pattern=r'^[-\\w\\._\\(\\)]+$'),\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/msrest/serialization.py\", line 594, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/msrest/serialization.py\", line 674, in validate\n    raise ValidationError(key, name, value)\nmsrest.exceptions.ValidationError: Parameter 'deployment_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'.\n",
    "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600155874.172015-2230-46984444222089/AnsiballZ_azure_rm_deployment.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_deployment', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 702, in <module>\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 698, in main\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 471, in __init__\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py\", line 348, in __init__\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 479, in exec_module\n  File \"/tmp/ansible_azure_rm_deployment_payload_x0kviwmq/ansible_azure_rm_deployment_payload.zip/ansible/modules/cloud/azure/azure_rm_deployment.py\", line 554, in deploy_template\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py\", line 279, in create_or_update\n    **operation_config\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py\", line 199, in _create_or_update_initial\n    'deploymentName': self._serialize.url(\"deployment_name\", deployment_name, 'str', max_length=64, min_length=1, pattern=r'^[-\\w\\._\\(\\)]+$'),\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/msrest/serialization.py\", line 594, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/msrest/serialization.py\", line 674, in validate\n    raise ValidationError(key, name, value)\nmsrest.exceptions.ValidationError: Parameter 'deployment_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'.\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}
```

The module should either have a subresource variable (just like azure_rm_resource) or let slashes in the `deployment_name`.
