### ISSUE TITLE
Add support for vnet rules on MySQL, MariaDB and PostgreSQL servers

### ISSUE THREAD

**Issue by maartendekeizer** [ansible-collections/azure#310]
##### SUMMARY
We need vnet rules on MySQL, MariaDB and PostgreSQL servers so we can define which vnets/subnet can access the database server when using a service endpoint.
Related Azure CLI documentation https://docs.microsoft.com/en-us/cli/azure/mariadb/server/vnet-rule?view=azure-cli-latest / https://docs.microsoft.com/en-us/cli/azure/mysql/server/vnet-rule?view=azure-cli-latest / https://docs.microsoft.com/en-us/cli/azure/postgres/server/vnet-rule?view=azure-cli-latest

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- azure_rm_mysqlserver
- azure_rm_mariadbserver
- azure_rm_postgresqlserver

##### ADDITIONAL INFORMATION

Example of defining vnet rules allong with the database server
```yaml
- name: Create MariaDB server
  azure_rm_mariadbserver:
    name: "{{ mariadb_servername }}"
    ...
    vnet_rules:
      - name: "my-rule"
        network_name: "my-vnet"
        subnet: "my-subnet"
```

Example of defining vnet rules separate (like database server firewall rules)
```yaml
- name: Create MariaDB server
  azure_rm_mariadbvnetrule:
    name: "my-rule"
    server_name: "my-db-server"
    network_name: "my-vnet"
    subnet: "my-subnet"
```
