### ISSUE TITLE
azure_rm_virtualmachinescaleset updates is single instance although upgrade policy is manual

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible-collections/azure#911]
##### SUMMARY

When using the module azure.azcollection.azure_rm_virtualmachinescaleset and updating the image and defining upgrade_policy to Manual the process still updates one instance 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_virtualmachinescaleset

##### ANSIBLE VERSION

```paste below
quay.io/ansible/awx-ee:0.6.0
```

and

```paste below
2.10
```

##### COLLECTION VERSION

```paste below
1.9
```

##### OS / ENVIRONMENT

Centos

##### STEPS TO REPRODUCE

```yaml
- name: Update image reference on scaleset
  azure.azcollection.azure_rm_virtualmachinescaleset:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    resource_group: '{{ resource_group }}'
    name: vmss_name
    upgrade_policy: Manual
    image:
      name: '{{ image_name }}'
      resource_group: '{{ resource_group }}'
```

##### EXPECTED RESULTS

Should not update a single instance.
